# Generated by Django 5.0 on 2026-05-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_remove_employee_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('label', models.CharField(max_length=100, verbose_name='Коротка назва (для бейджа)')),
                ('icon', models.CharField(help_text='Наприклад: fa-mobile-alt', max_length=60, verbose_name='Іконка Font Awesome')),
                ('description', models.TextField(verbose_name='Опис послуги')),
                ('price_display', models.CharField(help_text='Наприклад: від 250 ₴', max_length=60, verbose_name='Ціна (текст)')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, help_text='Числове значення для сортування', max_digits=10, null=True, verbose_name='Ціна від (₴)')),
                ('time_estimate', models.CharField(help_text='Наприклад: 30 хв – 2 год', max_length=100, verbose_name='Час виконання')),
                ('warranty', models.CharField(help_text='Наприклад: 12 місяців', max_length=100, verbose_name='Гарантія')),
                ('features', models.TextField(help_text='По одному пункту на рядок', verbose_name='Що входить')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['sort_order'],
            },
        ),
    ]
